### ISSUE TITLE
Custom enchanted book

### ISSUE THREAD

**Issue by Snowad14** [xpple/SeedMapper#10]
Is there a way to find a specific enchantment? I tried the same as the / give but the command didn't work. I don't know if it's easy to implement but it would be really useful

**Comment by xpple** [comment]
Yeah, that's possible. I was somewhat planning to add this, actually.

**Comment by xpple** [comment]
This turns out much harder than I thought it would be.

**Comment by xpple** [comment]
Closed with [this commit](https://github.com/xpple/SeedMapper/commit/61b73a4b83f10af2c43e31652f51ee4f8ada517e).
