### ISSUE TITLE
Special Highliting SeedOverlay

### ISSUE THREAD

**Issue by Krashgamer** [xpple/SeedMapper#23]
~~A list to exclude Block types from being Highlighted on seedoverlay~~ and one to highlight Blocks in a special color if added to another list.

example commands:

~~/seedmapper:seedoverlay hide add/del <Block>~~

/seedmapper:seedoverlay highlight add/del <Block>

**Comment by xpple** [comment]
The first one has been implemented already! Try `/seedmapper config ignored add <block>`

**Comment by Krashgamer** [comment]
oh ok.. sorry for the "duplicate" suggestion then

**Comment by xpple** [comment]
To make sure, you wish to be able to customize the overlay colour?

**Comment by xpple** [comment]
Closed by [this commit](https://github.com/xpple/SeedMapper/commit/7cb384a0f45219b7e3565e787cf1cdf1004a0dfc).
