### ISSUE TITLE
[Suggestion] Range setting for /highlight

### ISSUE THREAD

**Issue by erxson** [xpple/SeedMapper#25]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xpple** [comment]
Although I can basically guess what your problem and solution is, it would be nice if you could fill in the template text (or remove it and describe your issue without). This also applies to #26.

Details aside, this issue sounds like a good addition to me.

**Comment by xpple** [comment]
Closed with [this commit](https://github.com/xpple/SeedMapper/commit/fc11112e1508ec15f8f018eb61280a47292e13dd).
