### ISSUE TITLE
[Suggestion] Add 3 seeds support (overworld, nether and end)

### ISSUE THREAD

**Issue by erxson** [xpple/SeedMapper#26]
**Is your feature request related to a problem? Please describe.**
Auto seed set doesnt work on Paper and etc. server, because there're 3 different seeds.

**Describe the solution you'd like**
Just make 3 different seeds for 3 different dimensions

**Comment by xpple** [comment]
Did you find a solution to your problem?

**Comment by erxson** [comment]
> Did you find a solution to your problem?

txt with 3 seeds and ctrl+c, ctrl+v
