### ISSUE TITLE
Add support for setting dimensions manually on servers with custom dimension names.

### ISSUE THREAD

**Issue by Wide-Cat** [xpple/SeedMapper#28]
Some servers have custom names for their dimensions, even though they are essentially just the vanilla dimension. This causes the mod to return the error 'Dimension {dimension} is not supported'. This is obviously intended and a necessary feature, but when the server for some reason changes the name of the vanilla dimensions it causes the mod to essentially be unable to function at all, even if it were fully able to.

Since it can happen that they are just the vanilla dimension but with a custom name, I suggest a way to manually assign the correct vanilla dimension to the custom name, so the mod can work as intended. As an example, `/seedmapper:config dimension overworld` will make the mod use the overworld logic for the current dimension, despite any custom naming.

**Comment by xpple** [comment]
Well, I am glad to tell you there's already a way to do this. Instead of executing `/seedmapper:locate biome badlands`, just execute `/source in overworld run seedmapper:locate biome badlands`.

**Comment by Wide-Cat** [comment]
oh nice
