### ISSUE TITLE
1.18 | y<0 rendering highlights

### ISSUE THREAD

**Issue by scouttiger** [xpple/SeedMapper#34]
**Describe the bug**
No rendering lower then Y0

**To Reproduce**
open the mod in 1.18.x and highlight blocks underneath y0 diamond_ore for example

**Expected behavior**
it shows both diamond_ore aswell as deepslate_diamond_ore when highlighting, so it also shows diamonds below Y0

**Additional context**
No further context needed

**Comment by xpple** [comment]
SeedMapper's ore highlighting feature won't work for ores in the overworld for Minecraft 1.18.
