### ISSUE TITLE
Its more of a Question than an Issue "Dimension not supported"

### ISSUE THREAD

**Issue by Fnrs-Wlan** [xpple/SeedMapper#36]
As it says i got the Message "Dimension not Supported farmwelt-2"
The Seed is Correct and all so i just want to ask if theres a way to make Seedmapper ignore the custom Name for the Dimension.
Its the Normal Overworld but just renamed.
Checked the Seed and everything perfectly aligns

**Comment by xpple** [comment]
Yes, there is a way to force SeedMapper to use the overworld as dimension. Prefix any of your commands with `/seedmapper:source in overworld run <your command>`. For example `/seedmapper:locate feature slimechunk` becomes `/seedmapper:source in overworld run seedmapper:locate feature slimechunk`. Let me know if that works.

**Comment by Fnrs-Wlan** [comment]
Thanks it works very well. 
I love using Seedmapper! Good work on that
Have a nice day

**Comment by Fnrs-Wlan** [comment]
I tested it on the Server
Im using the latest Seedmapper version on Version 1.17.1 the World Version is 1.16.5 and is called farmwelt-2
I use the command /source in minecraft:overworld run highlight block redstone_ore 
But it doesnt align with the Ores
Did i miss smth?

**Comment by xpple** [comment]
If the world version doesn’t match the client’s version you can force SeedMapper to use the desired version again by using the `/seedmapper:source` command. Your command will be as follows: `/seedmapper:source  versioned 1.16.5 in minecraft:overworld run highlight block redstone_ore`.

**Comment by Fnrs-Wlan** [comment]
/seedmapper:source versioned? Its just marked red and the command you said doesnt work for me
Sry for bothering you so long xd

**Comment by Fnrs-Wlan** [comment]
WOW this works like a Charm!
Thx for your time, i rly love your work.

**Comment by xpple** [comment]
Thanks, I appreciate it! The `/seedmapper:source` command is really powerful if you know how to use it.

**Comment by Utkarsh2007Upadhyay** [comment]
> Can you use source only for Seedmapper commands or for EVERY Command?

Ig it's only for seedmapper's commands.

**Comment by xpple** [comment]
Indeed, it only works for SeedMapper's commands.
