### ISSUE TITLE
Seedmapper doesn't show up in the commands.

### ISSUE THREAD

**Issue by hinabl** [xpple/SeedMapper#39]
**Describe the bug**
Sometimes all of the seedmapper commands doesnt show up in the chat. Any of the commands such as "/seedmapper:*" but the commands does still work. It just doesnt show up
![unknown (1)](https://user-images.githubusercontent.com/79749008/153806941-b2eacada-262d-479c-b3c9-b82ed361e3ea.png)
![nowork](https://media.discordapp.net/attachments/558991753345236992/942662301654323220/unknown.png)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Will show possible commands such as "/seedmapper:*"
![should work](https://media.discordapp.net/attachments/558991753345236992/942662181487521882/unknown.png)

**Additional context**
Add any other context about the problem here. In the case of a crash, include the crash log (`.minecraft/logs`).

**Comment by ItsEmpa** [comment]
To add to this, it DOES work if you relog

**Comment by hinabl** [comment]
if you mean by work is showing the commands.. no.. the working screenshot is from a random youtube video since i cant take a screenshot of it cause it doesn't show up on me.

but if you mean the commands works, then yes, they do work just not showing up.

btw i have tried restarting the game, deleting the config, and restarting my whole system, seems to still not work properly

**Comment by hinabl** [comment]
> if you mean by work is showing the commands.. no.. the working screenshot is from a random youtube video since i cant take a screenshot of it cause it doesn't show up on me.
> 
> but if you mean the commands works, then yes, they do work just not showing up.
> 
> btw i have tried restarting the game, deleting the config, and restarting my whole system, seems to still not work properly

found a way to fix it(in my case)

-doing normal reconnect(leaving the server and rejoining) seems to not work
-but reconnecting using a mod like client commands seems to have made it work properly again??

**Comment by ItsEmpa** [comment]
weird, when i reconnect normally the commands show (havent tried using `/crelog` with clientcommands tho)

**Comment by xpple** [comment]
Are you playing Singleplayer or Multiplayer?

**Comment by ItsEmpa** [comment]
This happens to me on multiplayer

**Comment by xpple** [comment]
Alright. Are you using any other mods? If so, please send a list of them.

**Comment by xpple** [comment]
What about you, @hinabl?

**Comment by hinabl** [comment]
mods I use:
Accurate Block Placement
Better Third Person
CIT Resewn
Client Commands
Cull Leaves
Ears
EntityCulling-Fabric
Fabric API
Farsight Mod
FerriteCore
Iris
LambDynamicLights
LazyDFU
litematica
Lithium
MaLiLib
Mod Menu
Presence Footsteps
Reese's Sodium Options
Replay Mod
SeedCrackerX
SeedMapper
Slyde
Sodium
Sodium Extra

>>Yup thats all of them

**Comment by ItsEmpa** [comment]
this is the list of mods i use
```
AdvancedChatCore-1.18.1-1.4.0.jar
AdvancedChatHUD-1.18.1-1.2.0.jar
advancementinfo-1.18-fabric0.43.1-1.3.jar
animatica-0.3+1.18.jar
architectury-3.4.9.jar
BackupFilesNames.txt
bedrock-miner-1.0.0-for-minecraft-1.18.1.jar
borderless-mining-1.1.1+1.18.jar
Capes-1.2.2+1.18.jar
cem-0.7.0.jar
CITResewn-0.9.1+1.18.1.jar
clickthrough-1.18-fabric0.43.1-0.4.jar
clientcommands-2.6.jar
cloth-api-3.1.61.jar
cloth-config-6.1.48-fabric.jar
completeconfig-lib-1.3.3.jar
continuity-1.0.3+1.18.jar
CraftPresence-Fabric-1.18.1-Release-1.8.8.jar
cullleaves-2.3.2.jar
DevMode-1.1.jar
dynamic-fps-2.1.0.jar
emoji-type-1.0.1.jar
enhancedblockentities-0.5+1.18.jar
entity-texture-features-2.1.3.jar
EntityCulling-Fabric-1.3.3.jar
fabric-api-0.46.2+1.18.jar
fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
fabrishot-1.6.0.jar
fastopenlinksandfolders-1.0.1.jar
ferritecore-4.0.0-fabric.jar
IKnowWhatImDoing-4.0.0-fabric.jar
indium-1.0.2-alpha2+mc1.18.1.jar
instantkill-1.0.0.jar
iris-mc1.18.1-1.2.0-pre.jar
item-model-fix-1.0.3+1.18.jar
itemscroller-fabric-1.18.1-0.15.0.jar
jsmacros-1.18-FABRIC-1.6.5-beta-fb43d5c.jar
lambdabettergrass-1.2.2+1.17.jar
lambdynamiclights-2.1.0+1.17.jar
lazydfu-0.1.2.jar
litematica-fabric-1.18.1-0.10.1.jar
lithium-fabric-mc1.18.1-0.7.7.jar
malilib-fabric-1.18.1-0.11.5.jar
midnightlib-0.3.1.jar
minihud-fabric-1.18.1-0.21.3.jar
mining-cooldown-fix-1.18.1-1.0.0.jar
modmenu-3.0.1.jar
morechathistory-1.18-1.1.0.jar
multiconnect-1.5.10.jar
nbttooltip-1.5.0-fabric.jar
NoChatLag-1.1.0.jar
nofade-1.18-2.0.1.jar
notenoughcrashes-4.1.4+1.18.1-fabric.jar
Pick-Block-Pro-1.5.6-mc1.18.1.jar
puzzle-1.1.0.jar
rebind-narrator-1.18-1.0.0.jar
reeses_sodium_options-mc1.18.1-1.4.0.jar
screenshot-to-clipboard-1.0.7-fabric.jar
seedcrackerX-2.11.4.jar
seedmapper-b1.4.7.jar
skin-swapper-fabric-3.1.0.jar
slotlock-1.0.4-BETA+1.18.jar
smoothboot-fabric-1.18-1.7.0.jar
sodium-extra-mc1.18.1-0.3.8.jar
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar
starlight-1.0.0+fabric.d0a3220.jar
statuseffecttimer-1.1.0+1.18.1.jar
TieFix-1.8.0.jar
tooltipfix-1.0.4-1.18.jar
tweakeroo-fabric-1.18.1-0.12.1.jar
WI-Zoom-1.3-MC1.18.1.jar
XaerosWorldMap_1.20.1_Fabric_1.18.jar
Xaeros_Minimap_22.1.2_Fabric_1.18.jar
yosbr-0.1.1.jar
```

**Comment by erxson** [comment]
same issue

**Comment by xpple** [comment]
I will look into this. I wonder, does it also happen with just SeedMapper (and the Fabric API) in your `mods` folder?

**Comment by erxson** [comment]
Yes
![image](https://user-images.githubusercontent.com/50082485/160371279-905f3c09-0fd5-4638-971d-6c250b572e11.png)

**Comment by hinabl** [comment]
Haven't updated it to the latest version yet since I'm still using 1.18.1 and the version where this occured, seems to not happen yet. It does happen randomly and haven't been really using seed stuff atm

**Comment by xpple** [comment]
Closing for now, feel free to reopen if it wasn't fixed.
