### ISSUE TITLE
Version "1.18.2" was not found.

### ISSUE THREAD

**Issue by PanCake0428** [xpple/SeedMapper#45]
**Describe the Issue**
Whenever I type in a command for the latest version of seedmapper the command doesn't work(When I have the seed configured), and it sends the error message of "Version "1.18.2" was not found." Is this a bug in the mod itself or is it something I did wrong?

**Expected behavior**
On older versions of Minecraft the block was highlighted whenever I typed in the highlight command.

Thanks!

**Comment by xpple** [comment]
Could you provide the `latest.log` file?

**Comment by white-devil42** [comment]
> **Describe the Issue** Whenever I type in a command for the latest version of seedmapper the command doesn't work(When I have the seed configured), and it sends the error message of "Version "1.18.2" was not found." Is this a bug in the mod itself or is it something I did wrong?
> 
> **Expected behavior** On older versions of Minecraft the block was highlighted whenever I typed in the highlight command.
> 
> Thanks!

isn't that because ore generation is not added for 1.18.2?

**Comment by xpple** [comment]
No, this is different. Right now SeedMapper should automatically fall back to 1.17 when 1.18 isn't supported. It should not however return an error like "Version "1.18.2" was not found.".

**Comment by PanCake0428** [comment]
[latest.log](https://github.com/xpple/SeedMapper/files/8509993/latest.log)

**Comment by PanCake0428** [comment]
There are too many .log files and I don't think I can find it. Perhaps I should try recreating the issue?

**Comment by PanCake0428** [comment]
[latest.log](https://github.com/xpple/SeedMapper/files/8512689/latest.log)

**Comment by white-devil42** [comment]
> No, this is different. Right now SeedMapper should automatically fall back to 1.17 when 1.18 isn't supported. It should not however return an error like "Version "1.18.2" was not found.".

really, then i too had this problem when trying to locate a pillager outpost in 1.18.2

**Comment by shikiko** [comment]
Still getting a 1.18.2 was not found even after using the latest 1.5.3

**Comment by xpple** [comment]
Have you also updated SeedCrackerX to the latest version (the [pre-release](https://github.com/19MisterX98/SeedcrackerX/releases))?

**Comment by shikiko** [comment]
yeah, using the latest commands via /sm still shows that 1.18.2 error

**Comment by xpple** [comment]
Could you send your `latest.log`?
