### ISSUE TITLE
autocomplete is dead for some commands

### ISSUE THREAD

**Issue by erxson** [xpple/SeedMapper#46]
+-same issue with sm:locate
![image](https://user-images.githubusercontent.com/50082485/165077391-660fae82-1d4e-4425-856a-4d0fb52a40dc.png)

**Comment by erxson** [comment]
but works for enchanted goals
![image](https://user-images.githubusercontent.com/50082485/165077505-a46d7272-6e95-4e9a-8f73-5e36f68f4ad4.png)

**Comment by xpple** [comment]
@erxson, is this still a problem?
