### ISSUE TITLE
Version "1.18.2" was not found.

### ISSUE THREAD

**Issue by PedaretKhor** [xpple/SeedMapper#48]
[05:09:82] [Render thread/WARN]: Syntax exception for client-sided command '/sm:highlight block diamond_ore'
com.mojang.brigadier.exceptions.CommandSyntaxException: Version "1.18.2" was not found.

**Comment by PedaretKhor** [comment]
my problem solved but it shows everything wrong i created a word with 1.18.2 seed and i tried to locate some biomes and highlight some ores but it shows them wrong

**Comment by PedaretKhor** [comment]
@xpple

**Comment by andi-makes** [comment]
1.18 Overworld generation is currently not supported - nether and end should work fine though.
