### ISSUE TITLE
Version "1.19" was not found. 

### ISSUE THREAD

**Issue by Geromo94** [xpple/SeedMapper#49]
Hello, i use "seedmapper-1.5.5.jar" for Minecraft 1.19, but i got this error on chat :CCC

**Comment by xpple** [comment]
Could you send a list of the mods you are using?

**Comment by mdo992** [comment]
I'm also getting this issue when only when using the latest version of SeedCrackerX.

**Comment by mdo992** [comment]
This was fixed by using the latest SeedCracker build.
