### ISSUE TITLE
Please add 1.12.2 support

### ISSUE THREAD

**Issue by Sans003** [xpple/SeedMapper#5]

**Comment by xpple** [comment]
Hey I'm sorry I'm only seeing now, for some reason I don't get any notifications from this repo. 1.12 and below is planned to be supported somewhat soon. In any case thanks for checking out my mod!

**Comment by Sans003** [comment]
Hey,
That’s totally fine but thank you for replying and letting me know

-Sans

**Comment by Sans003** [comment]
The reason why I needed is for basehunting on anarchy servers that’s why it
would be REALLY important

**Comment by xpple** [comment]
I see. I'll let you know when it's there.

**Comment by Sans003** [comment]
Awesome, thank you so much

**Comment by Sans003** [comment]
I have another question.
Does this work in the nether?

**Comment by xpple** [comment]
Yes, it should. Though nether terrain is subject to more drastical generation terrain modifications than the overworld terrain.

**Comment by xpple** [comment]
Also, for questions unrelated to this issue, please go to [the Discord](https://discord.xpple.dev/) instead :).

**Comment by xpple** [comment]
Forgot to close this issue.
