### ISSUE TITLE
Version 1.19.2 is not found

### ISSUE THREAD

**Issue by plz-Enter-name** [xpple/SeedMapper#52]
**Describe the bug**
A clear and concise description of what the bug is. Make sure to always use the latest (stable) version of SeedMapper before opening an issue.
When I type "/sm:highlight block diamond_ore" I get an error saying "Version 1.19.2 is not found"

**To Reproduce**
Steps to reproduce the behavior.
type /sm:highlight block diamond_ore

**Expected behavior**
highlight diamond_ore

**Additional context**
Add any other context about the problem here. In the case of a crash, include the crash log (`.minecraft/logs`).

**Comment by xpple** [comment]
Ah, I forgot to update the libraries. Do note however that versions 1.18 and 1.19 aren’t supported yet, so your command wouldn’t have worked if you are on a 1.19 server either way.

**Comment by plz-Enter-name** [comment]
NOOOOOOOOOOOOOO
