### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by kittenvr** [xpple/SeedMapper#57]
**Describe the bug**
When i try to launch the game it crashes

**To Reproduce**
Launch the game with these mods
![image](https://user-images.githubusercontent.com/103120356/218283723-5f578961-7a55-4531-a1c3-53069ecc9856.png)

**Expected behavior**
i doesn't crash and just opens the game

**Additional context**
[log](https://mclo.gs/4SPGTUv)

**Comment by andi-makes** [comment]
SeedMapper requires [BetterConfig](https://modrinth.com/mod/betterconfig) as of the latest version, could you try adding it to your mods? That should fix the problem

**Comment by kittenvr** [comment]
> SeedMapper requires [BetterConfig](https://modrinth.com/mod/betterconfig) as of the latest version, could you try adding it to your mods? That should fix the problem

thanks that fixes it

**Comment by xpple** [comment]
> SeedMapper requires [BetterConfig](https://modrinth.com/mod/betterconfig) as of the latest version, could you try adding it to your mods? That should fix the problem

That mod is included in SeedMapper, so you shouldn't need to do that.

I actually had the same issue during development, for me updating the Fabric installation fixed the issue.
