### ISSUE TITLE
locate any amount of an item

### ISSUE THREAD

**Issue by kittenvr** [xpple/SeedMapper#58]
**Is your feature request related to a problem? Please describe.**
make it so you can do /sm:locate loot any diamond

**Describe the solution you'd like**
it would find the nearest diamond in a chest

**Describe alternatives you've considered**

**Additional context**

**Comment by xpple** [comment]
Just do `/sm:locate loot 1 diamond`.

**Comment by kittenvr** [comment]
> Just do `/sm:locate loot 1 diamond`.

Then it wil only find 1 and i just want to find the closest

**Comment by xpple** [comment]
It will find possibly more than one, if the loot container happens to contain more than one item.
