### ISSUE TITLE
Add terrainversion changes

### ISSUE THREAD

**Issue by quangei** [xpple/SeedMapper#63]
I want command like `/sm:terrainversion <version>`, it will changes the version what locate, block hightlight, ... use to simulate
`/sm:source versioned <version>` doesn't work

**Comment by xpple** [comment]
What does it say when you try `/sm:source versioned <version> run sm:terrainversion`?

**Comment by xpple** [comment]
`/sm:terrainversion` tries to determine the version the terrain was generated in by counting the amount of blocks that don't match the supposed terrain. To change what version is used for commands like `/sm:locate` you can do `sm:source versioned <version> sm:locate ...`.

By the way, 1.19 terrain is not supported by SeedMapper, meaning that you will get incorrect results.
