### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by skaffa** [xpple/SeedMapper#66]
**Describe the bug**
None of the features that require the seed are showing correct information. The locator shows completely incorrect coordinates, the overlay shows completely wrong blocks.

**To Reproduce**
Join the server I'm in, enter the correct seed in the config, use the /sm:locate or /sm:overlay command

**Expected behavior**
I expect it to give me correct coordinated to structures within the world and to show accurate overlays.

**Additional context**
I copied the exact seed as provided by SeedCracker. When testing in singleplayer, i can confirm that the seed is correct.
I'm on version 1.20.2

**Comment by RacoonDog** [comment]
> Disclaimer, This mod does not yet support terrain generation of Minecraft versions above 1.17.1
taken from the readme
