### ISSUE TITLE
1.20.1 : Highlight command doesn't allow deepslate ore selection

### ISSUE THREAD

**Issue by ashton727** [xpple/SeedMapper#68]
**Describe the bug**
The 1.20.1 version of the mod does not seem to actually be configured for 1.20.1. It does not allow any selection of deepslate ores and it appears the predicted placement of ores is incorrect. 

**To Reproduce**
get seed, highlight deepslate_diamond_ore or gold etc.

**Expected behavior**
Should display ores correctly and allow selection of all ore blocks

**Comment by xpple** [comment]
That is correct, SeedMapper does not yet support 1.18+ terrain generation. The reason the mod itself is updated to these later Minecraft versions is to maintain backwards compatibility with older versions. Many people use mods like ViaFabricPlus to play on older servers while being able to use the latest version of other mods. You can configure the version you want SeedMapper to use by using the `/sm:source` command. Closing this in favour of #42.
