### ISSUE TITLE
Minecraft Freezes (dosen't crash) when locating strctures not in the current dimension 

### ISSUE THREAD

**Issue by vanvac** [xpple/SeedMapper#69]
**Describe the bug**
Mc version: 1.21.3 (fabric)
runnung java23
seedMapper version : 2.0.0-beta.1

The bug causes Minecraft to freeze indefinetly (not crash) and causes the console to get spammed by error messages when using the /sm:locate feature structure <structure> command and tryin to locate a structure that is not in the current dimension. This is kinda User error because why would you try locate end cities in the owerworld and the /sm:source command exists to run it in a different dimension but i feel that it the bug should be handled in code to prevent freeze
**To Reproduce**
launch mc with seedMapper 1.21.3 
go into a world (likely with cheats/commands on for testing)
get the seed using the /seed command
do /cconfig SeedMapper seed set <seed>
then in owerworld run the /sm:locate feature structure <structure> command with a sturcutre that dosen't exist in the overworld e.g. end_city 
after running Minecraft proceesds to Freeze indefinetly (making it not responding) 
force closing the game using a launcher such as prism launcher, or multi mc shows the console which is also frozen for a little time beacause the console has been spammed by error messages form the Mod. (bad structure type 20 or dimension 0)

**Expected behavior**
Maybe a warning that you are looking for the structure in the wrong dimension, suggestion to use the /sm:source command to run it in that dimension 

**Additional context**
some sreenshots
![Screenshot 2024-11-02 212137](https://github.com/user-attachments/assets/7fbbf716-6a13-4807-8b27-17631b3a320f)
![Screenshot 2024-11-02 212205](https://github.com/user-attachments/assets/4f69554d-bb7c-4423-9c8d-e4fd042536fb)

**Comment by vanvac** [comment]
![image](https://github.com/user-attachments/assets/a8653b43-f041-4a8c-9888-7895816ebd31)
 the command that you should run to get the structure in a different dimension is
/sm:source in <dimension> (<as player/entity>)<--- opional <run> and for <run> do sm:locate <feature/biome> <boime or slimechunk/structure> <structure>

**Comment by vanvac** [comment]
/sm:source in <dimension> (as <player/entity>)<--- opional run <command> and for <command> do sm:locate <feature/biome> <boime or slimechunk/structure> <structure>

**Comment by xpple** [comment]
Thank you for posting the logs, I will look into it.

**Comment by vanvac** [comment]
update SeedMapper-2.0.0-beta.2 and future fixed Download can be found on Modrinth: https://modrinth.com/mod/seedmapper
