### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by NathanVH8** [xpple/SeedMapper#70]
- **SeedMapper version**: 2.0.0-beta4+1.21
- **Java version**: Java 23
- **Operating system**: Windows 10
- **System architecture**:  AMD64

**Describe the bug**
Only three of the /sm: commands show up and are usable

**To Reproduce**
Load Minecraft 1.21 on Fabric 0.16.9 with Fabric API 0.102.0+1.21 open a world, set the seed, and type /sm:
Only /sm:checkseed, /sm:locate, and /sm:source show up in the command suggestions.

**Expected behavior**
All of the commands listed in the wiki.

Screenshot attached with only three commands showing in the suggested commands.
![2024-11-05_14 43 03](https://github.com/user-attachments/assets/7a786672-e05e-4bb7-92dc-c0cf26fb4a85)

**Comment by vanvac** [comment]
Cubiomes can estimate terrian height but idk who well that will work for the seedoverlay command

**Comment by NathanVH8** [comment]
But in doing so you've removed the entire reason I downloaded this mod. I specifically wanted to check for terrain differences and terrain versions on a world that was generated between 1.13 and 1.16.5

**Comment by xpple** [comment]
Oh that's still possible! Just download the latest version on the 1.0.0 branch of SeedMapper and use ViaFabricPlus or something alike to connect to older servers. I suggest using [SeedMapper 1.6.1](https://modrinth.com/mod/seedmapper/version/1.6.1). I intend to maintain the 1.0.0 branch for at least some time to support needs like yours.
