### ISSUE TITLE
Java 23/21

### ISSUE THREAD

**Issue by Jumima67** [xpple/SeedMapper#76]
**Context**
- **SeedMapper version**: 2.0.1
- **Java version**: 23.0.1/21.0.5
- **Operating system**: Windows 11
- **System architecture**: amd64

So I am running a instance over prismlauncher and I want to to install SeedMapper on 1.21.3 and then it tells me to use Java 23, but when I then use Java 23, it tells me that Java 23 is not compatible with this instance. I might just be dumb and just not understand something, if that's the case just tell me.

**Comment by vanvac** [comment]
under where you set java version check the box that says "skip compatability checks"

**Comment by vanvac** [comment]
![image](https://github.com/user-attachments/assets/b1a32f25-a1e3-40ed-a081-f7aa937e0c75)

**Comment by Jumima67** [comment]
That did it thanks!
